### ISSUE TITLE
a few hints...

### ISSUE THREAD

**Issue by ianni67** [fiblan/webcam-virtual-background#1]
Thank you Fiblan for sharing. This is a very interesting project, with lots of suggestions.
I added a few "issues" providing some (hopefully) useful hints.

**Comment by ianni67** [comment]
This app is so interesting that would deserve a bit more work.
As a further nagging I would add:
- Changing the socket communication to multithread processing, with a thread that computes the mask and the other that composes the mask with the background.
- (this is easy!) adding the possibility to use a video file (in "loop") or a video from a second camera as the background.  Loop-ing a (background) video can be obtained by adding a simple control when retrieving each frame from the (background) video. Something like: 
```
ret, frame = cap.read() 
    if ret:
        cv2.imshow("Image", frame)
    else:
       print('no video')
       cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
```

**Comment by fiblan** [comment]
Thanks @ianni67,  I think your hints deserve a more attention. In the next few days, I split this issue in other smaller issues.  If you want to do it yourself, you are welcome.

**Comment by fiblan** [comment]
I'm closing this issue. 

Splitted in #3 #4 #5 #6 #7 #8
