### ISSUE TITLE
[Suggestion] video as a background

### ISSUE THREAD

**Issue by ianni67** [fiblan/webcam-virtual-background#7]
(this is easy!) adding the possibility to use a video file (in "loop") or a video from a second camera as the background. Loop-ing a (background) video can be obtained by adding a simple control when retrieving each frame from the (background) video. Something like:

```
ret, frame = cap.read() 
    if ret:
        cv2.imshow("Image", frame)
    else:
       print('no video')
       cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
```

**Comment by fiblan** [comment]
added looping video feature
